@startuml

hide circle
title Example of Classes Diagram 

Class Person {
    name
    age
}

Class Teacher {
    course
    workExperience
}

Class Student {
    course
    studentGroup
}

Person <|-- Teacher

Person <|-- Student

Teacher"1" --> "+"Student : teaches

Student"1" --> "+"Teacher : studies

@enduml
